CREATE TABLE boards(
  ID SERIAL PRIMARY KEY,
  NAME TEXT NOT NULL
);

CREATE TABLE lists (
  ID SERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  SORT INT NOT NULL,
  board_id INT NOT NULL REFERENCES boards(id)
);

CREATE TABLE cards (
  ID SERIAL PRIMARY KEY,
  DESCRIPTION TEXT NOT NULL,
  SORT INT NOT NULL,
  list_id INT NOT NULL REFERENCES lists(id)
);
